version: "3.7"

volumes:
  prometheus-data:
    name: prometheus-data
  grafana-data:
    name: grafana-data

networks:
  default:
    ipam:
      config:
        - subnet: 172.22.0.0/16

services:
  web:
    image: goldeneye/web
    container_name: web
    ports:
      - 443:443
    volumes:
      - /websrv:/websrv
      - /etc/letsencrypt/live:/etc/letsencrypt/live:ro
      - /etc/letsencrypt/archive:/etc/letsencrypt/archive:ro
      - /mnt/store0:/mnt/store0:ro
      - ./config/web:/etc/nginx:ro

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:10.8.4
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      - JELLYFIN_PublishedServerUrl=goldeneye:8096 #optional
    volumes:
      - ./data/jellyfin:/config
      - /mnt/store0/shows:/data/tv:ro
      - /mnt/store0/movies:/data/movies:ro
      - /mnt/store0/other:/data/other:ro
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional

  samba:
    image: goldeneye/samba
    container_name: samba
    ports:
      - 139:139
      - 445:445
    volumes:
      - ./config/samba/smb.conf:/etc/samba/smb.conf:ro
      - /mnt/store1/drive:/mnt/store1/drive:rw

  unifi:
    image: jacobalberty/unifi
    container_name: unifi
    ports:
      - 3478:3478/udp
      - 6789:6789/tcp
      - 8080:8080/tcp
      - 8443:8443/tcp
      - 8843:8843/tcp
      - 8880:8880/tcp
      - 10001:10001/udp
    volumes:
      - ./data/unifi:/unifi
    environment:
      - TZ=America/Los_Angeles

  unbound:
    image: klutchell/unbound
    container_name: unbound
    ports:
      - 53:5053/udp
    volumes:
      - ./config/unbound:/etc/unbound:ro

  minecraft:
    image: openjdk:18-slim
    container_name: minecraft
    ports:
      - 25565:25565
    volumes:
      - ./data/minecraft:/minecraft:rw
    working_dir: /minecraft
    command: "java -Xmx8192M -Xms8192M -Dfml.readTimeout=90 -Dfml.ignorePatchDiscrepancies=true -jar server.jar nogui"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - grafana-data:/var/lib/grafana
    user: '104'
    depends_on:
      - prometheus

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    extra_hosts:
      goldeneye: 172.22.0.1
    ports:
      - 9090:9090
    volumes:
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    depends_on:
      - cadvisor

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

  boinc:
    image: boinc/client:nvidia
    container_name: boinc
    network_mode: host
    pid: host
    volumes:
      - ./data/boinc:/var/lib/boinc
    environment:
      - BOINC_GUI_RPC_PASSWORD=admin
      - BOINC_CMD_LINE_OPTIONS=--allow_remote_gui_rpc
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  dcgm-exporter:
    image: nvcr.io/nvidia/k8s/dcgm-exporter:2.4.5-2.6.7-ubuntu20.04
    container_name: dcgm-exporter
    ports:
      - 9400:9400
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  octoklip:
    image: doyleish/octoklip
    ports:
      - 8888:80
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    volumes:
      - ./data/octoprint:/octoprint
      - ./config/klipper/printer.cfg:/home/klipper/.config/printer.cfg
